name: Update TMDB Trending Data

on:
  schedule:
    # 每6小时运行一次
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install axios canvas
        
    - name: Generate trending data
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        node scripts/generate-trending-data.js
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || git commit -m "Update trending data $(date '+%Y-%m-%d %H:%M:%S')"
        git push